version: '3'

services:
    app:
        image: xpub/xpub-elife:${XPUB_VERSION}
        command: >
            /bin/bash -c "
                until echo > /dev/tcp/postgres/5432; do sleep 1; done
                npx pubsweet server
            "
        ports:
            - 3000:3000
        depends_on:
            - postgres
        environment:
            NODE_ENV: production
            NODE_CONFIG: '{
                "pubsweet-client": {
                    "API_ENDPOINT": "/api"
                },
                "pubsweet-server": {
                    "baseUrl": "${PUBSWEET_BASEURL}",
                    "secret": "somesecret",
                    "hostname": "${PUBSWEET_HOSTNAME}"
                },
                "password-reset": {
                    "url": "${PUBSWEET_BASEURL}/password-reset"
                },
                "pubsweet-component-ink-backend": {
                    "inkEndpoint": "https://demo--ink.elifesciences.org",
                    "email": "fake",
                    "password": "fake"
                },
                "auth-orcid": {
                    "clientID": "${ORCID_CLIENT_ID}",
                    "clientSecret": "${ORCID_CLIENT_SECRET}"
                },
                "meca": {
                    "s3": {
                        "params": {
                          "Bucket": "${S3_BUCKET}"
                        }
                    }
                }

            }'
            PGHOST: postgres
            PGUSER: xpub
    postgres:
        image: postgres:10
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: xpub
        volumes:
            - postgres-volume:/var/lib/postgresql/data
    bootstrap:
        image: bash:4.3.48
        command: >
            /usr/local/bin/bash -c "until echo > /dev/tcp/app/3000; do sleep 1; done"
        depends_on:
            - app

volumes:
    postgres-volume:
