version: '3'

services:
    app:
        image: xpub/xpub-elife:${XPUB_VERSION}
        command: >
            /bin/bash -c "
                until echo > /dev/tcp/postgres/5432; do sleep 1; done
                node app
            "
        ports:
            - 3000:3000
        depends_on:
            - postgres
        env_file:
          - .env
        environment:
            NODE_ENV: production
            PGHOST: postgres
            PGUSER: xpub
            NODE_CONFIG: '{
                "auth-orcid": {
                    "sandbox": true
                },
                "meca": {
                    "s3": {
                        "params": {
                          "Bucket": "${S3_BUCKET}"
                        }
                    }
                }
            }'

    postgres:
        image: postgres:10
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: xpub
        volumes:
            - postgres-volume:/var/lib/postgresql/data
    bootstrap:
        image: bash:4.3.48
        command: >
            /usr/local/bin/bash -c "until echo > /dev/tcp/app/3000; do sleep 1; done"
        depends_on:
            - app

volumes:
    postgres-volume:
