version: '3'

services:
    app:
        image: xpub/xpub-elife:${XPUB_VERSION}
        command: >
            /bin/bash -c "
                until echo > /dev/tcp/postgres/5432; do sleep 1; done
                node app
            "
        ports:
            - 3000:3000
        depends_on:
            - postgres
        environment:
            NODE_ENV: production
            NODE_CONFIG_ENV:
            NODE_CONFIG: '{
                "scienceBeam":{
                    "url":"http://sciencebeam:8075/api/convert"
                },
                "meca": {
                    "s3": {
                        "params": {
                          "Bucket": "${S3_BUCKET}"
                        }
                    }
                }
            }'
            PGHOST:
            PGUSER:
            PGPASSWORD:
            PGDATABASE:
            PGPORT:
            ORCID_CLIENT_ID:
            ORCID_CLIENT_SECRET:
            PUBSWEET_BASEURL:
            PUBSWEET_HOSTNAME:
            PUBSWEET_SECRET:
            MECA_SFTP_HOST:
            MECA_SFTP_PORT:
            MECA_SFTP_USERNAME:
            MECA_SFTP_PASSWORD:
            MECA_SFTP_REMOTEPATH:
            MECA_API_KEY:
            NEW_RELIC_ENABLED:
            NEW_RELIC_APP_NAME:
            NEW_RELIC_LICENSE_KEY:

    sciencebeam:
        image: elifesciences/sciencebeam:${SCIENCEBEAM_TAG}
        command: ./server.sh \
            --host=0.0.0.0 --port=8075 \
            --grobid-url http://grobid:8070/api
        ports:
        - "8075:8075"
        networks:
        - default
        - sciencebeam-internal
        restart: always
        depends_on:
        - grobid

    grobid:
        image: lfoppiano/grobid:${GROBID_TAG}
        environment:
        - JAVA_OPTS=-Xmx1g
        ports:
        - "8070:8070"
        networks:
        - sciencebeam-internal
        healthcheck:
            test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8070"]
            interval: 10s
            timeout: 10s
            retries: 5
        restart: always

    postgres:
        image: postgres:10
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${PGUSER}
            POSTGRES_DB: ${PGDATABASE}
            #PGHOST:
            #PGUSER:
            #PGPASSWORD:
            #PGDATABASE:
            #PGPORT:
        volumes:
            - postgres-volume:/var/lib/postgresql/data

    bootstrap:
        image: bash:4.3.48
        command: >
            /usr/local/bin/bash -c "until echo > /dev/tcp/app/3000; do sleep 1; done"
        depends_on:
            - app

volumes:
    postgres-volume:

networks:
    sciencebeam-internal:
        internal: true
